<div class="col-md-4">
                            <div class="zt_indr_item">
                                <a class="zt_link_list" href="[field:typelink/]">
                                    <div class="zt_link_list_img">
                                        <img src="{dede:field name='arcpic'/}" alt="[field:fulltitle/]" /> 
                                        <div class="zt_link_list_text zt_show_online">[field: typename / ]</div>
                                    </div>
                               </a>
                                
                            </div>
                        </div>