<?php
$z[0]=Array("arclist","\r\n                                    <img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\"/>\r\n                                    ",180,346);
$z[0][4]['row']="1";
$z[1]=Array("channelartlist","\r\n                                    <dl class=\"zt_dl\">\r\n                                        <dt>\r\n                                            <span class=\"zt_hasShow_list glyphicon glyphicon-plus-sign\"></span>\r\n                                            <a href='{dede:field name=' typeurl '",489,810);
$z[2]=Array("field","",812,841);
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n                                            <li>\r\n                                                - <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                                            </li>\r\n                                            ",968,1242);

?>