<?php
$z[0]=Array("type","\r\n                <h2>[field:typename/]</h2> ",0,68);
$z[1]=Array("field","",329,359);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",361,390);
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n                            <li>\r\n                                - <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                            </li>\r\n                            ",485,695);

?>