<li>
                                    <a href="[field:arcurl/]" class="row vertical-middle-sm">
                                        <div class="zt_listview_img col-md-4"><img src="[field:litpic/]" alt="[field:fulltitle/]"></div>
                                        <div class="zt_listview_text zt_listview_text_right col-md-8">
                                            <h3>[field:title/]</h3>
                                            <p>[field:infos/]</p>
                                        </div>
                                    </a>
                                </li>