<a href="[field:arcurl/]" class="fl" target="_blank"><img src="[field:litpic/]" width="104" height="69" class="fl" alt="[field:fulltitle/]"></a>
                        <div class="intro">
                            <a href="[field:arcurl/]" class="tit" target="_blank">[field:title/]</a>
                            <a href="[field:arcurl/]" target="_blank">[field:info/]...</a>
                        </div>