<div class="col-md-6">
                            <div class="zt_indr_item">
                                <div class="zt_indr_item_img">
                                    <img src="[field:litpic/]" alt="[field:fulltitle/]" />
                                </div>
                                <div class="zt_indr_item_list">
                                    <a href="[field:arcurl /]">[field:title /]</a>
                                    <div><a href='{dede:field name=' typeurl '/}'>了解更多></a></div>
                                </div>
                                
                            </div>
                        </div>