<?php
$z[0]=Array("field","",232,262);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",264,293);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n                                            <li>\r\n                                                - <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                                            </li>\r\n                                            ",420,694);

?>