<li>
						<a href="[field:arcurl/]" class="img"><img src="[field:litpic/]" width="146" height="97" class="fl" alt="[field:title function='html2text(@me)'/]"></a>
                            <div class="intro">
                                <a href="[field:arcurl/]" class="tit" >[field:title/]</a>
								<a href="[field:arcurl/]">[field:infos/]...</a>
                                <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                            </div>
                        </li>