<?php
$z[0]=Array("channelartlist","\r\n                                    <dl class=\"zt_dl\">\r\n                                        <dt>\r\n                                            <span class=\"zt_hasShow_list glyphicon glyphicon-plus-sign\"></span>\r\n                                            <a href='{dede:field name=' typeurl '",375,696);
$z[1]=Array("field","",698,727);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n                                            <li>\r\n                                                - <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                                            </li>\r\n                                            ",854,1128);

?>