<?php
$z[0]=Array("arclist","\r\n                                    <img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\" /> ",180,310);
$z[0][4]['row']="1";
$z[1]=Array("field","",572,602);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",604,633);
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n                                            <li>\r\n                                                - <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                                            </li>\r\n                                            ",802,1076);

?>