<li>
                                <a href="{dede:field.download/}" >
                                    <div class="intro">
                                        <p>[field:title/]</p>
                                        <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                                        <div class="sign">
                                            <div class="d"></div>
                                        </div>
                                    </div>
                                </a>
                            </li>