<?php
$z[0]=Array("field","",202,232);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",234,263);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n                                            <li>\r\n                                                - <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                                            </li>\r\n                                            ",364,638);

?>