<dl>
                                        <dt>
                                            <span class="glyphicon glyphicon-plus-sign"></span>
                                            <a href='{dede:field name=' typeurl '/}'>{dede:field name='typename'/}</a></dt>
                                        <dd>
                                            {dede:arclist}
                                            <li>
                                                - <a href="[field:arcurl /]">[field:title /]</a>
                                            </li>
                                            {/dede:arclist}
                                        </dd>
                                    </dl>