<li>
                        <a href="[field:arcurl/]">
                            <img src="[field:litpic/]" width="292" height="205" class="fl"  alt="[field:fulltitle/]" >
                            <p class="fz16"><span >[dede:field.shorttitle /]</span></p>
                            <p>[field:infos/]...</p>
                            <div class="line"></div>
                        </a>
                    </li>