<?php
$z[0]=Array("typeurl","",33,49);
$z[1]=Array("typename","",51,68);
$z[2]=Array("arcurl","",710,725);
$z[3]=Array("litpic","",749,764);
$z[4]=Array("title","",806,846);
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("arcurl","",944,959);
$z[6]=Array("title","",974,988);
$z[7]=Array("arcurl","",1011,1026);
$z[8]=Array("infos","",1028,1042);
$z[9]=Array("pubdate","",1089,1136);
$z[9][4]['function']="MyDate('Y-m-d',@me)";

?>