<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	

<field:download itemname="下载文档" autofield="1" notsend="0" type="addon" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:download>


<field:jsgg itemname="技术规格" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jsgg>
