<div class="zt_item_img_wrapper">
                                    <img src="{dede:field.typeimg/}" alt="[field:fulltitle/]" />
                                </div>
                                <div class="zt_item_content_wrapper">
                                    <dl class="zt_dl">
                                        <dt>
                                            <span class="zt_hasShow_list glyphicon glyphicon-plus-sign"></span>
                                            <a href='{dede:field name=' typeurl '/}'>{dede:field name='typename'/}</a></dt>
                                        <dd class="zt_dd zt_def_hide">
                                            {dede:arclist}
                                            <li>
                                                - <a href="[field:arcurl /]">[field:title /]</a>
                                            </li>
                                            {/dede:arclist}
                                        </dd>
                                    </dl>
                                </div>