<?php
$z[0]=Array("field","",81,102);
$z[0][4]['name']="typeimg";
$z[1]=Array("field","",512,542);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",544,573);
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n                                            <li>\r\n                                                - <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                                            </li>\r\n                                            ",700,974);

?>