<div class="col-md-4">
                            <div class="zt_indr_item">
                                <a class="zt_link_list" href="{dede:field name='typeurl'/}">
                                    <div class="zt_link_list_img">
                                        <img src="[field:typeimg/]" alt="{dede:field name='typename'/}" /> 
                                        <div class="zt_link_list_text zt_show_online">{dede:field name='typename'/}</div>
                                    </div>
                               </a>
                                
                            </div>
                        </div>