<?php
$z[0]=Array("arclist","\r\n                                    <img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\" /> ",180,310);
$z[0][4]['row']="1";
$z[1]=Array("field","",580,610);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",612,641);
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n                                            <li>\r\n                                                - <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                                            </li>\r\n                                            ",798,1080);
$z[3][4]['row']="5";
$z[4]=Array("field","",1243,1273);
$z[4][4]['name']="typeurl";

?>