<?php
$z[0]=Array("field","",218,248);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",250,279);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n                                            <li>\r\n                                                - <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                                            </li>\r\n                                            ",400,674);

?>