<li>
                            <a href="[field:arcurl/]"><img src="[field:litpic/]" width="93" height="62" class="fl" alt="[field:fulltitle/]"></a>
                            <div class="intro">
                                <a href="[field:arcurl/]">[field:title/]</a>
                                <p>TIME：[field:pubdate function="MyDate('Y-m-d',@me)"/]</p>
                            </div>
                        </li>