<?php
$z[0]=Array("include","",39,83);
$z[0][4]['filename']="headBaseRefer.htm";
$z[1]=Array("include","",260,298);
$z[1][4]['filename']="navBase.htm";
$z[2]=Array("type","\r\n                <h2>[field:typename/]</h2> ",409,489);
$z[2][4]['typeid']="80";
$z[3]=Array("arclist","\r\n                        <li>\r\n                            - <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                        </li>\r\n                        ",610,876);
$z[3][4]['typeid']="80";
$z[3][4]['titlelen']="42";
$z[3][4]['isweight']="Y";
$z[3][4]['orderby']="weigth";
$z[3][4]['orderway']="desc";
$z[4]=Array("field","",1349,1378);
$z[4][4]['name']="position";
$z[5]=Array("field","",1472,1491);
$z[5][4]['name']="title";
$z[6]=Array("field","",1625,1644);
$z[6][4]['name']="title";
$z[7]=Array("field","",1702,1722);
$z[7][4]['name']="writer";
$z[8]=Array("field","",1741,1793);
$z[8][4]['name']="pubdate";
$z[8][4]['function']="MyDate('Y-m-d',@me)";
$z[9]=Array("field","",1875,1893);
$z[9][4]['name']="body";
$z[10]=Array("pagebreak","",2116,2133);
$z[11]=Array("prenext","",2374,2399);
$z[11][4]['get']="pre";
$z[12]=Array("prenext","",2440,2466);
$z[12][4]['get']="next";
$z[13]=Array("include","",2636,2675);
$z[13][4]['filename']="footBase.htm";
$z[14]=Array("include","",2693,2739);
$z[14][4]['filename']="bottomBaseRefer.htm";

?>