<?php
$z[0]=Array("include","",39,83);
$z[0][4]['filename']="headBaseRefer.htm";
$z[1]=Array("include","",260,298);
$z[1][4]['filename']="navBase.htm";
$z[2]=Array("type","\r\n                <h2>[field:typename/]</h2> ",409,477);
$z[3]=Array("channelartlist","\r\n                        <li>\r\n                            - <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n                        </li>\r\n                        ",599,893);
$z[3][4]['titlelen']="42";
$z[3][4]['isweight']="Y";
$z[3][4]['orderby']="weigth";
$z[3][4]['orderway']="desc";
$z[4]=Array("field","",1366,1395);
$z[4][4]['name']="position";
$z[5]=Array("type","\r\n                <h2 class=\"zt_list_title\">[field:typename/]</h2> ",1463,1553);
$z[6]=Array("channelartlist","\r\n                        <div class=\"col-md-4\">\r\n                            <div class=\"zt_indr_item\">\r\n                                <a class=\"zt_link_list\" href=\"{dede:field name='typeurl'/}\">\r\n                                    <div class=\"zt_link_list_img\">\r\n                                        <img src=\"{dede:field.typeimg/}\" alt=\"{dede:field name='typename'/}\" /> \r\n                                        <div class=\"zt_link_list_text zt_show_online\">{dede:field name='typename'/}</div>\r\n                                    </div>\r\n                               </a>\r\n                                \r\n                            </div>\r\n                        </div>\r\n                        ",1699,2514);
$z[6][4]['titlelen']="42";
$z[6][4]['isweight']="Y";
$z[6][4]['orderby']="weigth";
$z[6][4]['orderway']="desc";
$z[7]=Array("include","",2612,2651);
$z[7][4]['filename']="footBase.htm";
$z[8]=Array("include","",2669,2715);
$z[8][4]['filename']="bottomBaseRefer.htm";

?>