<?php
$z[0]=Array("include","",39,83);
$z[0][4]['filename']="headBaseRefer.htm";
$z[1]=Array("include","",260,298);
$z[1][4]['filename']="navBase.htm";
$z[2]=Array("type","\r\n                <h2>[field:typename/]</h2> ",409,489);
$z[2][4]['typeid']="38";
$z[3]=Array("channel","\r\n                        <li>\r\n                            - <a href=\"[field:typelink /]\">[field:typename/]</a>\r\n                        </li>\r\n                        ",611,821);
$z[3][4]['typeid']="38";
$z[4]=Array("field","",1294,1323);
$z[4][4]['name']="position";
$z[5]=Array("type","\r\n                <h2 class=\"zt_list_title\">[field:typename/]</h2> ",1391,1481);
$z[6]=Array("field","",1662,1683);
$z[6][4]['name']="content";
$z[7]=Array("include","",1813,1852);
$z[7][4]['filename']="footBase.htm";
$z[8]=Array("include","",1870,1916);
$z[8][4]['filename']="bottomBaseRefer.htm";

?>