<?php
$z[0]=Array("include","",39,83);
$z[0][4]['filename']="headBaseRefer.htm";
$z[1]=Array("include","",260,298);
$z[1][4]['filename']="navBase.htm";
$z[2]=Array("type","\r\n                <h2>[field:typename/]</h2> ",409,477);
$z[3]=Array("channel","\r\n                        <li>\r\n                            - <a href=\"[field:typelink /]\">[field:typename/]</a>\r\n                        </li>\r\n                        ",599,797);
$z[4]=Array("field","",1270,1299);
$z[4][4]['name']="position";
$z[5]=Array("type","\r\n                <h2 class=\"zt_list_title\">[field:typename/]</h2> ",1367,1457);
$z[6]=Array("channel","\r\n                        <div class=\"col-md-4\">\r\n                            <div class=\"zt_indr_item\">\r\n                                <a class=\"zt_link_list\" href=\"[field:typelink /]\">\r\n                                    <div class=\"zt_link_list_img\">\r\n                                        <img src=\"[field:typeimg/]\" alt=\"[field:title function='html2text(@me)'/]\" /> \r\n                                        <div class=\"zt_link_list_text zt_show_online\">[field:typename/]</div>\r\n                                    </div>\r\n                               </a>\r\n                                \r\n                            </div>\r\n                        </div>\r\n                        ",1603,2329);
$z[7]=Array("include","",2427,2466);
$z[7][4]['filename']="footBase.htm";
$z[8]=Array("include","",2484,2530);
$z[8][4]['filename']="bottomBaseRefer.htm";

?>