<div class="col-md-4">
                            <div class="zt_indr_item">
                                <a class="zt_link_list" href="[field:arcurl/]">
                                    <div class="zt_link_list_img">
                                        <img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]" /> 
                                        <div class="zt_link_list_text zt_show_online">[field:title/]</div>
                                    </div>
                               </a>
                                
                            </div>
                        </div>