<li>
                                <a href="[field:arcurl/]" >
                                    <div class="intro">
                                        <p>[field:title/]</p>
                                        <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                                        <div class="sign"><div class="t"><img src="[field:litpic/]"></div>
                                            <div class="d"></div>
                                        </div>
                                    </div>
                                </a>
                            </li>