<div class="swiper-slide">
                                    <a href="[field:typeurl/]"><img src="[field:litpic/]" alt="[field:fulltitle/]"></a>
                                    <div class="swiper_content_text">
                                        <h3>[field:title/]</h3>
                                        <p>[field:infos/]</p>
                                    </div>
                                </div>