<?php
$z[0]=Array("field","",111,130);
$z[0][4]['name']="title";
$z[1]=Array("global","",131,157);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",198,220);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",260,311);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",836,871);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename/]",977,1017);
$z[6]=Array("type","[field:typename/]",1367,1407);
$z[7]=Array("field","",1523,1552);
$z[7][4]['name']="position";
$z[8]=Array("channel","\r\n	                       <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n	                       ",1807,2030);
$z[8][4]['typeid']="18";
$z[8][4]['type']="son";
$z[8][4]['currentstyle']="<a href='~typelink~' class='on'>~typename~</a>";
$z[9]=Array("list","\r\n                            <tr>\r\n                                <td><a href=\"[field:download/]\" class=\"fl\">[field:title/]</a></td>\r\n                                <td>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</td>\r\n                                <td><a href=\"[field:download/]\" >&nbsp;</a></td>\r\n                            </tr>\r\n                            ",2529,2950);
$z[9][4]['pagesize']="6";
$z[9][4]['titlelen']="40";
$z[10]=Array("pagelist","",3306,3377);
$z[10][4]['listitem']="info,index,end,pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",3544,3581);
$z[11][4]['filename']="footer.htm";

?>