<?php
$z[0]=Array("field","",103,125);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",166,188);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",228,279);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",447,487);
$z[3][4]['filename']="headquote.htm";
$z[4]=Array("include","",554,589);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename/]",692,732);
$z[6]=Array("arclist","\r\n                        <li>\r\n                            <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"93\" height=\"62\" class=\"fl\" alt=\"[field:fulltitle/]\"></a>\r\n                            <div class=\"intro\">\r\n                                <a href=\"[field:arcurl/]\">[field:title/]</a>\r\n                                <p>TIME：[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</p>\r\n                            </div>\r\n                        </li>\r\n                        ",1262,1816);
$z[6][4]['row']="3";
$z[6][4]['typeid']="17";
$z[6][4]['titlelen']="35";
$z[7]=Array("include","",4310,4347);
$z[7][4]['filename']="footer.htm";

?>