<?php
$z[0]=Array("field","",111,133);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",174,196);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",236,287);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",391,431);
$z[3][4]['filename']="headquote.htm";
$z[4]=Array("include","",854,889);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename/]",995,1035);
$z[6]=Array("type","[field:typename/]",1403,1443);
$z[7]=Array("field","",1555,1584);
$z[7][4]['name']="position";
$z[8]=Array("channel","\r\n	                       <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n	                       ",1839,2062);
$z[8][4]['typeid']="18";
$z[8][4]['type']="son";
$z[8][4]['currentstyle']="<a href='~typelink~' class='on'>~typename~</a>";
$z[9]=Array("list","\r\n                            <tr>\r\n                                <td><a href=\"http://www.qdzitn.com[field:download/]\" class=\"fl\">[field:title/]</a></td>\r\n                                <td>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</td>\r\n                                <td><a href=\"http://www.qdzitn.com[field:download/]\" ></a></td>\r\n                            </tr>\r\n                            ",2561,3018);
$z[9][4]['pagesize']="6";
$z[9][4]['titlelen']="40";
$z[10]=Array("pagelist","",3374,3445);
$z[10][4]['listitem']="info,index,end,pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",3612,3649);
$z[11][4]['filename']="footer.htm";

?>