<?php
$z[0]=Array("field","",103,122);
$z[0][4]['name']="title";
$z[1]=Array("global","",123,149);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",190,212);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",252,303);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",829,864);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename/]",967,1007);
$z[6]=Array("arclist","\r\n                        <li>\r\n                            <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"93\" height=\"62\" class=\"fl\" alt=\"[field:fulltitle/]\"></a>\r\n                            <div class=\"intro\">\r\n                                <a href=\"[field:arcurl/]\">[field:title/]</a>\r\n                                <p>TIME：[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</p>\r\n                            </div>\r\n                        </li>\r\n                        ",1519,2073);
$z[6][4]['row']="3";
$z[6][4]['typeid']="17";
$z[6][4]['titlelen']="35";
$z[7]=Array("include","",4560,4597);
$z[7][4]['filename']="footer.htm";

?>