<?php
$z[0]=Array("arclist","\r\n                                    <img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\">\r\n                                    ",176,333);
$z[1]=Array("channelartlist","\r\n                                    <dl class=\"zt_dl\">\r\n                                        <dt>\r\n                                            <span class=\"zt_hasShow_list glyphicon glyphicon-plus-sign\"></span>\r\n                                            <a href='{dede:field name=' typeurl '",476,797);
$z[2]=Array("field","",799,828);
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n                                            <li>\r\n                                                - <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                                            </li>\r\n                                            ",955,1229);

?>