<div class="swiper-slide">
                                    <a href="[field:typeurl/]">
                                        <img src="[field:litpic/]" alt="[field:fulltitle/]">
                                        <div class="swiper_content_text">
                                            <div class="swiper_text_inner">
                                                <h3>[field:title/]</h3>
                                                <p>[field:infos/]</p>
                                            </div>
                                        </div>
                                    </a>
                                </div>