<?php
$z[0]=Array("channel","\r\n		        <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		        ",178,318);
$z[0][4]['typeid']="1";
$z[0][4]['type']="son";
$z[0][4]['row']="8";
$z[1]=Array("channel","\r\n		        <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		        ",447,588);
$z[1][4]['typeid']="18";
$z[1][4]['type']="son";
$z[1][4]['row']="6";
$z[2]=Array("channel","\r\n		        <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		        ",831,971);
$z[2][4]['typeid']="2";
$z[2][4]['type']="son";
$z[2][4]['row']="6";
$z[3]=Array("channel","\r\n		        <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		        ",1067,1207);
$z[3][4]['typeid']="5";
$z[3][4]['type']="son";
$z[3][4]['row']="6";
$z[4]=Array("channel","\r\n		        <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		        ",1310,1450);
$z[4][4]['typeid']="4";
$z[4][4]['type']="son";
$z[4][4]['row']="6";
$z[5]=Array("global","",2276,2302);
$z[5][4]['name']="cfg_powerby";

?>