<?php
$z[0]=Array("field","",111,130);
$z[0][4]['name']="title";
$z[1]=Array("global","",131,157);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",198,220);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",260,311);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",835,870);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename/]",973,1013);
$z[6]=Array("type","[field:typename/]",1386,1426);
$z[7]=Array("field","",1543,1572);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n                        <li><img src=\"[field:litpic/]\" width=\"89\" height=\"62\"  data-img=\"[field:litpic/]\" alt=\"[field:fulltitle/]\"></li>\r\n                        ",2154,2369);
$z[8][4]['infolen']="60";
$z[8][4]['titlelen']="28";
$z[9]=Array("include","",2504,2541);
$z[9][4]['filename']="footer.htm";

?>