<?php
$z[0]=Array("field","",111,133);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",174,196);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",236,287);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",391,431);
$z[3][4]['filename']="headquote.htm";
$z[4]=Array("include","",853,888);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename/]",991,1031);
$z[6]=Array("type","[field:typename/]",1404,1444);
$z[7]=Array("field","",1557,1586);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n                        <li><img src=\"[field:litpic/]\" width=\"89\" height=\"62\"  data-img=\"[field:litpic/]\" alt=\"[field:fulltitle/]\"></li>\r\n                        ",2192,2407);
$z[8][4]['infolen']="60";
$z[8][4]['titlelen']="28";
$z[9]=Array("include","",2542,2579);
$z[9][4]['filename']="footer.htm";

?>