<?php
$z[0]=Array("global","",111,137);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",181,211);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",248,275);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",412,452);
$z[3][4]['filename']="headquote.htm";
$z[4]=Array("include","",1890,1925);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist","\r\n                        <li>\r\n                        <a href=\"[field:arcurl/]\" >\r\n                  <img src=\"[field:litpic/]\" width=\"276\" height=\"181\" class=\"fl\" alt=\"[field:fulltitle/]\" ></a>\r\n                  <h2><a href=\"[field:arcurl/]\" >[field:title/]</a></h2>\r\n                  <a href=\"[field:arcurl/]\" ><p class=\"more fl\">read more</p></a> \r\n              </li>\r\n             ",4733,5246);
$z[5][4]['type']="image";
$z[5][4]['typeid']="26";
$z[5][4]['titlelen']="40";
$z[5][4]['row']="12";
$z[5][4]['isweight']="Y";
$z[5][4]['orderby']="weight";
$z[5][4]['orderway']="desc";
$z[6]=Array("arclist","\r\n                        <li>\r\n                            <div class=\"time\">\r\n                                <span class=\"fz22\">[field:pubdate function=\"MyDate('m.d',@me)\"/]</span>\r\n                                <span>[field:pubdate function=\"MyDate('Y',@me)\"/]</span>\r\n                            </div>\r\n                            <a href=\"[field:arcurl/]\" >[field:title/]</a>\r\n                        </li>\r\n                     ",5805,6353);
$z[6][4]['typeid']="4";
$z[6][4]['titlelen']="60";
$z[6][4]['row']="6";
$z[6][4]['isweight']="Y";
$z[6][4]['orderby']="weight";
$z[6][4]['orderway']="desc";
$z[7]=Array("flink","[field:link /]",10560,10633);
$z[7][4]['row']="40";
$z[7][4]['titlelen']="40";
$z[7][4]['typeid']="0";
$z[8]=Array("global","",10860,10886);
$z[8][4]['name']="cfg_powerby";

?>