<?php
$z[0]=Array("global","",111,137);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",181,211);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",248,275);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",412,452);
$z[3][4]['filename']="headquote.htm";
$z[4]=Array("include","",2159,2194);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist","\r\n                        <li>\r\n                        <a href=\"[field:arcurl/]\" target=\"_blank\">\r\n                  <img src=\"[field:litpic/]\" width=\"276\" height=\"181\" class=\"fl\" alt=\"[field:fulltitle/]\" ></a>\r\n                  <h2><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></h2>\r\n                  <a href=\"[field:arcurl/]\" target=\"_blank\"><p class=\"more fl\">read more</p></a> \r\n              </li>\r\n             ",3246,3759);
$z[5][4]['type']="image";
$z[5][4]['typeid']="26";
$z[5][4]['titlelen']="40";
$z[5][4]['row']="12";
$z[6]=Array("arclist","\r\n                        <a href=\"[field:arcurl/]\" class=\"fl\" target=\"_blank\"><img src=\"[field:litpic/]\" width=\"104\" height=\"69\" class=\"fl\" alt=\"[field:fulltitle/]\"></a>\r\n                        <div class=\"intro\">\r\n                            <a href=\"[field:arcurl/]\" class=\"tit\" target=\"_blank\">[field:title/]</a>\r\n                            <a href=\"[field:arcurl/]\" target=\"_blank\">[field:info/]...</a>\r\n                        </div>\r\n                    ",4331,4893);
$z[6][4]['type']="image";
$z[6][4]['typeid']="20";
$z[6][4]['titlelen']="60";
$z[6][4]['infolen']="100";
$z[6][4]['flag']="c";
$z[6][4]['row']="1";
$z[7]=Array("arclist","\r\n                        <li>\r\n                            <div class=\"time\">\r\n                                <p class=\"fz22\">[field:pubdate function=\"MyDate('d',@me)\"/]</p>\r\n                                <p>[field:pubdate function=\"MyDate('Y.m',@me)\"/]</p>\r\n                            </div>\r\n                            <a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a>\r\n                        </li>\r\n                     ",4970,5476);
$z[7][4]['typeid']="19";
$z[7][4]['titlelen']="60";
$z[7][4]['row']="2";
$z[8]=Array("flink","[field:link /]",9262,9335);
$z[8][4]['row']="10";
$z[8][4]['titlelen']="40";
$z[8][4]['typeid']="0";
$z[9]=Array("global","",9591,9617);
$z[9][4]['name']="cfg_powerby";

?>