<?php
$z[0]=Array("include","",39,83);
$z[0][4]['filename']="headBaseRefer.htm";
$z[1]=Array("include","",260,298);
$z[1][4]['filename']="navBase.htm";
$z[2]=Array("type","\r\n                <h2>[field:typename/]</h2> ",409,489);
$z[2][4]['typeid']="68";
$z[3]=Array("channelartlist","\r\n                    <dl class=\"zt_dl \">\r\n                        <dt>\r\n                            <span class=\"zt_hasShow_list glyphicon glyphicon-plus-sign\"></span>\r\n                            <a href='{dede:field name=' typeurl '/}'>{dede:field name='typename'/}</a></dt>\r\n                        <dd class=\"zt_dd zt_def_hide\">\r\n                            {dede:arclist}\r\n                            <li>\r\n                                - <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                            </li>\r\n                            {/dede:arclist}\r\n                        </dd>\r\n                    </dl>\r\n                    ",566,1274);
$z[3][4]['typeid']="68";
$z[4]=Array("field","",1720,1749);
$z[4][4]['name']="position";
$z[5]=Array("type","\r\n                <h2 class=\"zt_list_title\">[field:typename/]</h2> ",1817,1907);
$z[6]=Array("channelartlist","\r\n                        <div class=\"col-md-4\">\r\n                            <div class=\"zt_indr_item\">\r\n                                <a class=\"zt_link_list\" href=\"{dede:field name=' typeurl '/}\">\r\n                                    <div class=\"zt_link_list_img\">\r\n                                        <img src=\"{dede:field.typeimg/}\" alt=\"[field:fulltitle/]\" /> \r\n                                        <div class=\"zt_link_list_text zt_show_online\">{dede:field name='typename'/}</div>\r\n                                    </div>\r\n                               </a>\r\n                                \r\n                            </div>\r\n                        </div>\r\n                        ",2053,2799);
$z[7]=Array("include","",2897,2936);
$z[7][4]['filename']="footBase.htm";
$z[8]=Array("include","",2954,3000);
$z[8][4]['filename']="bottomBaseRefer.htm";

?>