<?php
$z[0]=Array("field","",103,122);
$z[0][4]['name']="title";
$z[1]=Array("global","",123,149);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",190,212);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",252,303);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",642,677);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",5474,5511);
$z[5][4]['filename']="footer.htm";

?>