<?php
$z[0]=Array("field","",111,130);
$z[0][4]['name']="title";
$z[1]=Array("global","",131,157);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",198,220);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",260,311);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",646,681);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename/]",784,824);
$z[6]=Array("type","[field:typename/]",1231,1271);
$z[7]=Array("field","",1391,1420);
$z[7][4]['name']="position";
$z[8]=Array("channel","\r\n	                <li> <a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n	                ",1622,1759);
$z[8][4]['type']="son";
$z[9]=Array("list","\r\n                        <li>\r\n						<a href=\"[field:arcurl/]\" class=\"img\"><img src=\"[field:litpic/]\" width=\"146\" height=\"97\" class=\"fl\" alt=\"[field:title function='html2text(@me)'/]\"></a>\r\n                            <div class=\"intro\">\r\n                                <a href=\"[field:arcurl/]\" class=\"tit\" >[field:title/]</a>\r\n								<a href=\"[field:arcurl/]\">[field:infos/]...</a>\r\n                                <span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>\r\n                            </div>\r\n                        </li>\r\n                    ",2022,2654);
$z[9][4]['pagesize']="8";
$z[9][4]['infolen']="80";
$z[9][4]['titlelen']="42";
$z[10]=Array("pagelist","",3886,3957);
$z[10][4]['listitem']="info,index,end,pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",4059,4096);
$z[11][4]['filename']="footer.htm";

?>