<?php
$z[0]=Array("field","",114,136);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",177,206);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",246,304);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",408,448);
$z[3][4]['filename']="headquote.htm";
$z[4]=Array("include","",849,884);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename/]",1213,1253);
$z[6]=Array("field","",1403,1432);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n                    <li>\r\n                        <a href=\"[field:arcurl/]\">\r\n                            <img src=\"[field:litpic/]\" width=\"292\" height=\"205\" class=\"fl\"  alt=\"[field:fulltitle/]\" >\r\n                            <p class=\"fz16\"><span >[field:title/]</span></p>\r\n                            <p>[field:infos/]...</p>\r\n                            <div class=\"line\"></div>\r\n                        </a>\r\n                    </li>\r\n				",1542,2053);
$z[7][4]['pagesize']="6";
$z[7][4]['infolen']="150";
$z[7][4]['titlelen']="40";
$z[8]=Array("pagelist","",3312,3383);
$z[8][4]['listitem']="info,index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("arclist","\r\n                        <li><a href=\"[field:arcurl/]\" >[field:title/]</a></li>\r\n                        ",4767,4942);
$z[9][4]['typeid']="26";
$z[9][4]['pagesize']="6";
$z[9][4]['titlelen']="40";
$z[10]=Array("include","",5082,5119);
$z[10][4]['filename']="footer.htm";

?>