<?php
$z[0]=Array("field","",111,130);
$z[0][4]['name']="title";
$z[1]=Array("global","",131,157);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",198,227);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",267,325);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",828,863);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist","\r\n            <li><img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\"></li>\r\n			",945,1093);
$z[5][4]['type']="image";
$z[5][4]['pagesize']="1";
$z[5][4]['typeid']="34";
$z[6]=Array("type","[field:typename/]",1252,1292);
$z[7]=Array("field","",1446,1475);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n                    <li>\r\n                        <a href=\"[field:arcurl/]\">\r\n                            <img src=\"[field:litpic/]\" width=\"292\" height=\"205\" class=\"fl\"  alt=\"[field:fulltitle/]\" >\r\n                            <p class=\"fz16\"><span >[field:title/]</span></p>\r\n                            <p>[field:infos/]...</p>\r\n                            <div class=\"line\"></div>\r\n                        </a>\r\n                    </li>\r\n				",1585,2096);
$z[8][4]['pagesize']="6";
$z[8][4]['infolen']="150";
$z[8][4]['titlelen']="40";
$z[9]=Array("pagelist","",3355,3426);
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("arclist","\r\n                        <li><a href=\"[field:arcurl/]\" >[field:title/]</a></li>\r\n                        ",4815,4990);
$z[10][4]['typeid']="26";
$z[10][4]['pagesize']="6";
$z[10][4]['titlelen']="40";
$z[11]=Array("include","",5130,5167);
$z[11][4]['filename']="footer.htm";

?>