<?php
$z[0]=Array("field","",111,130);
$z[0][4]['name']="title";
$z[1]=Array("global","",131,157);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",198,227);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",267,325);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",828,863);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename/]",1213,1253);
$z[6]=Array("field","",1407,1436);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n                    <li>\r\n                        <a href=\"[field:arcurl/]\">\r\n                            <img src=\"[field:litpic/]\" width=\"292\" height=\"205\" class=\"fl\"  alt=\"[field:fulltitle/]\" >\r\n                            <p class=\"fz16\"><span >[field:title/]</span></p>\r\n                            <p>[field:infos/]...</p>\r\n                            <div class=\"line\"></div>\r\n                        </a>\r\n                    </li>\r\n				",1546,2057);
$z[7][4]['pagesize']="6";
$z[7][4]['infolen']="150";
$z[7][4]['titlelen']="40";
$z[8]=Array("pagelist","",3316,3387);
$z[8][4]['listitem']="info,index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("arclist","\r\n                        <li><a href=\"[field:arcurl/]\" >[field:title/]</a></li>\r\n                        ",4776,4951);
$z[9][4]['typeid']="26";
$z[9][4]['pagesize']="6";
$z[9][4]['titlelen']="40";
$z[10]=Array("include","",5091,5128);
$z[10][4]['filename']="footer.htm";

?>