<?php
$z[0]=Array("field","",111,134);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",175,197);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",237,288);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",528,568);
$z[3][4]['filename']="headquote.htm";
$z[4]=Array("include","",633,668);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename/]",771,811);
$z[6]=Array("type","[field:typename/]",1236,1276);
$z[7]=Array("field","",1392,1421);
$z[7][4]['name']="position";
$z[8]=Array("channel","\r\n	                <li> <a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n	                ",1623,1760);
$z[8][4]['type']="son";
$z[9]=Array("list","\r\n                        <li class=\"list_article_content\">\r\n						<a href=\"[field:arcurl/]\" class=\"img\"><img src=\"[field:litpic/]\" width=\"146\" height=\"97\" class=\"fl\" alt=\"[field:title function='html2text(@me)'/]\"></a>\r\n                            <div class=\"intro\">\r\n                                <a href=\"[field:arcurl/]\" class=\"tit\" >[field:title/]</a>\r\n								<a href=\"[field:arcurl/]\">[field:infos/]...</a>\r\n                                <span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>\r\n                            </div>\r\n                        </li>\r\n                    ",2023,2730);
$z[9][4]['pagesize']="8";
$z[9][4]['infolen']="80";
$z[9][4]['titlelen']="42";
$z[9][4]['isweight']="Y";
$z[9][4]['orderby']="weigth";
$z[9][4]['orderway']="desc";
$z[10]=Array("pagelist","",3962,4033);
$z[10][4]['listitem']="info,index,end,pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",4135,4172);
$z[11][4]['filename']="footer.htm";

?>