<?php
$z[0]=Array("field","",114,133);
$z[0][4]['name']="title";
$z[1]=Array("global","",134,160);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",201,230);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",270,328);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",831,866);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename/]",1194,1234);
$z[6]=Array("field","",1388,1417);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n                    <li>\r\n                        <a href=\"[field:arcurl/]\">\r\n                            <img src=\"[field:litpic/]\" width=\"292\" height=\"205\" class=\"fl\"  alt=\"[field:fulltitle/]\" >\r\n                            <p class=\"fz16\"><span >[field:title/]</span></p>\r\n                            <p>[field:infos/]...</p>\r\n                            <div class=\"line\"></div>\r\n                        </a>\r\n                    </li>\r\n				",1527,2038);
$z[7][4]['pagesize']="6";
$z[7][4]['infolen']="150";
$z[7][4]['titlelen']="40";
$z[8]=Array("pagelist","",3297,3368);
$z[8][4]['listitem']="info,index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("arclist","\r\n                        <li><a href=\"[field:arcurl/]\" >[field:title/]</a></li>\r\n                        ",4757,4932);
$z[9][4]['typeid']="26";
$z[9][4]['pagesize']="6";
$z[9][4]['titlelen']="40";
$z[10]=Array("include","",5072,5109);
$z[10][4]['filename']="footer.htm";

?>