<?php
$z[0]=Array("type","\r\n                                    <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n                                ",1142,1297);
$z[0][4]['typeid']="51";
$z[1]=Array("arclist","\r\n                                <li>\r\n                                    <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                                </li>\r\n                                ",1418,1654);
$z[1][4]['typeid']="51";
$z[2]=Array("type","\r\n                                    <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n                                ",1862,2017);
$z[2][4]['typeid']="56";
$z[3]=Array("arclist","\r\n                                <li>\r\n                                    <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                                </li>\r\n                                ",2138,2374);
$z[3][4]['typeid']="56";
$z[4]=Array("type","\r\n                                    <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n                                ",2582,2737);
$z[4][4]['typeid']="60";
$z[5]=Array("arclist","\r\n                                <li>\r\n                                    <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                                </li>\r\n                                ",2858,3094);
$z[5][4]['typeid']="60";
$z[6]=Array("type","\r\n                                    <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n                                ",3407,3562);
$z[6][4]['typeid']="61";
$z[7]=Array("arclist","\r\n                                <li>\r\n                                    <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                                </li>\r\n                                ",3683,3919);
$z[7][4]['typeid']="61";
$z[8]=Array("type","\r\n                                    <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n                                ",4127,4282);
$z[8][4]['typeid']="64";
$z[9]=Array("arclist","\r\n                                <li>\r\n                                    <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                                </li>\r\n                                ",4403,4639);
$z[9][4]['typeid']="64";
$z[10]=Array("type","\r\n                                    <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n                                ",4847,5001);
$z[10][4]['typeid']="9";
$z[11]=Array("arclist","\r\n                                <li>\r\n                                    <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                                </li>\r\n                                ",5122,5357);
$z[11][4]['typeid']="9";

?>