<?php
$z[0]=Array("field","",111,130);
$z[0][4]['name']="title";
$z[1]=Array("global","",131,157);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",198,227);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",267,325);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",665,700);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist","\r\n                            <li><a href=\"[field:arcurl/]\" target=\"blank\">[field:title/]</a></li>\r\n							",2374,2546);
$z[5][4]['typeid']="19";
$z[5][4]['titlelen']="25";
$z[5][4]['row']="6";
$z[6]=Array("arclist","\r\n                            <li><a href=\"[field:arcurl/]\" target=\"blank\">[field:title/]</a><span>[field:pubdate function=\"MyDate('Y.m',@me)\"/]</span></li>\r\n							",3149,3379);
$z[6][4]['typeid']="23";
$z[6][4]['titlelen']="32";
$z[6][4]['row']="3";
$z[7]=Array("arclist","\r\n                            <a href=\"[field:arcurl/]\"><div style=\"font-size:14px; font-weight:bold;\">[field:title/]</div>[field:info/]...</a>\r\n							",5445,5678);
$z[7][4]['typeid']="20";
$z[7][4]['infolen']="100";
$z[7][4]['titlelen']="42";
$z[7][4]['row']="1";
$z[8]=Array("include","",5811,5848);
$z[8][4]['filename']="footer.htm";

?>