<?php
$z[0]=Array("field","",111,133);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",174,203);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",243,301);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",405,445);
$z[3][4]['filename']="headquote.htm";
$z[4]=Array("include","",872,907);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist","\r\n                            <li><a href=\"[field:arcurl/]\" target=\"blank\">[field:title/]</a></li>\r\n							",2581,2753);
$z[5][4]['typeid']="19";
$z[5][4]['titlelen']="25";
$z[5][4]['row']="6";
$z[6]=Array("arclist","\r\n                            <li><a href=\"[field:arcurl/]\" target=\"blank\">[field:title/]</a><span>[field:pubdate function=\"MyDate('Y.m',@me)\"/]</span></li>\r\n							",3358,3588);
$z[6][4]['typeid']="23";
$z[6][4]['titlelen']="32";
$z[6][4]['row']="3";
$z[7]=Array("arclist","\r\n                            <a href=\"[field:arcurl/]\"><div style=\"font-size:14px; font-weight:bold;\">[field:title/]</div>[field:info/]...</a>\r\n							",5680,5913);
$z[7][4]['typeid']="20";
$z[7][4]['infolen']="100";
$z[7][4]['titlelen']="42";
$z[7][4]['row']="1";
$z[8]=Array("include","",6046,6083);
$z[8][4]['filename']="footer.htm";

?>