<?php
$z[0]=Array("field","",111,134);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",175,204);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",244,302);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",406,446);
$z[3][4]['filename']="headquote.htm";
$z[4]=Array("include","",869,904);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",6364,6401);
$z[5][4]['filename']="footer.htm";

?>