<?php
$z[0]=Array("include","",39,83);
$z[0][4]['filename']="headBaseRefer.htm";
$z[1]=Array("include","",271,309);
$z[1][4]['filename']="navBase.htm";
$z[2]=Array("type","\"/}<h2>[field:typename/]</h2> ",420,536);
$z[2][4]['typeid']="{dede:field name='typeid' function='getParentId(@me)'/";
$z[3]=Array("channelartlist","\"/}\r\n                    <dl class=\"zt_dl\">\r\n                        <dt>\r\n                            <span class=\"zt_hasShow_list glyphicon glyphicon-plus-sign\"></span>\r\n                            <a href='{dede:field name=' typeurl '/}'>{dede:field name='typename'/}</a></dt>\r\n                        <dd class=\"zt_dd zt_def_hide\">\r\n                            {dede:arclist}\r\n                            <li>\r\n                                - <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                            </li>\r\n                            {/dede:arclist}\r\n                        </dd>\r\n                    </dl>\r\n                    ",613,1374);
$z[3][4]['typeid']="{dede:field name='typeid' function='getParentId(@me)'/";
$z[4]=Array("field","",1820,1849);
$z[4][4]['name']="position";
$z[5]=Array("type","\r\n                <h2 class=\"zt_list_title\">[field:typename/]</h2> ",1917,2007);
$z[6]=Array("arclist","\r\n                        <div class=\"col-md-6\">\r\n                            <div class=\"zt_indr_item\">\r\n                                <div class=\"zt_indr_item_img\">\r\n                                    <img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\" />\r\n                                </div>\r\n                                <div class=\"zt_indr_item_list\">\r\n                                    <h2><a href=\"[field:arcurl /]\">[field:title /]</a></h2>\r\n                                    <div class=\"zt_indr_more\"><a href='{dede:field name=' typeurl '/}'>了解更多></a></div>\r\n                                </div>\r\n                                \r\n                            </div>\r\n                        </div>\r\n                        ",2251,3034);
$z[7]=Array("include","",3132,3171);
$z[7][4]['filename']="footBase.htm";
$z[8]=Array("include","",3189,3235);
$z[8][4]['filename']="bottomBaseRefer.htm";

?>