<?php
$z[0]=Array("include","",39,83);
$z[0][4]['filename']="headBaseRefer.htm";
$z[1]=Array("include","",271,309);
$z[1][4]['filename']="navBase.htm";
$z[2]=Array("include","",420,470);
$z[2][4]['filename']="product_left_item61.htm";
$z[3]=Array("field","",892,921);
$z[3][4]['name']="position";
$z[4]=Array("type","\r\n                <h2 class=\"zt_list_title\">[field:typename/]</h2> ",989,1079);
$z[5]=Array("arclist","\r\n                        <div class=\"col-md-6\">\r\n                            <div class=\"zt_indr_item\">\r\n                                <div class=\"zt_indr_item_img\">\r\n                                    <img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\" />\r\n                                </div>\r\n                                <div class=\"zt_indr_item_list\">\r\n                                    <h2><a href=\"[field:arcurl /]\">[field:title /]</a></h2>\r\n                                    <div class=\"zt_indr_more\"><a href='{dede:field name=' typeurl '/}'>了解更多></a></div>\r\n                                </div>\r\n                                \r\n                            </div>\r\n                        </div>\r\n                        ",1323,2106);
$z[6]=Array("include","",2204,2243);
$z[6][4]['filename']="footBase.htm";
$z[7]=Array("include","",2261,2307);
$z[7][4]['filename']="bottomBaseRefer.htm";

?>