<?php
$z[0]=Array("type","\r\n<h2>[field:typename/]</h2> ",0,64);
$z[0][4]['typeid']="51";
$z[1]=Array("channelartlist","\r\n    <dl class=\"zt_dl\">\r\n        <dt>\r\n            <span class=\"zt_hasShow_list glyphicon glyphicon-plus-sign\"></span>\r\n            <a href='{dede:field name=' typeurl '/}'>{dede:field name='typename'/}</a></dt>\r\n        <dd class=\"zt_dd zt_def_hide\">\r\n            {dede:arclist}\r\n            <li>\r\n                - <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n            </li>\r\n            {/dede:arclist}\r\n        </dd>\r\n    </dl>\r\n    ",109,608);
$z[1][4]['typeid']="51";

?>