<?php
$z[0]=Array("include","",39,83);
$z[0][4]['filename']="headBaseRefer.htm";
$z[1]=Array("include","",415,453);
$z[1][4]['filename']="navBase.htm";
$z[2]=Array("include","",564,614);
$z[2][4]['filename']="product_left_item51.htm";
$z[3]=Array("field","",1036,1065);
$z[3][4]['name']="position";
$z[4]=Array("type","\r\n                <h2 class=\"zt_list_title\">[field:typename/]</h2> ",1133,1223);
$z[5]=Array("field","",1931,1949);
$z[5][4]['name']="body";
$z[6]=Array("field","",2160,2178);
$z[6][4]['name']="jsgg";
$z[7]=Array("arclist","\r\n                                <div class=\"col-md-6\">\r\n                                    <div class=\"zt_indr_item\">\r\n                                        <div class=\"zt_indr_item_img\">\r\n                                            <img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\" />\r\n                                        </div>\r\n                                        <div class=\"zt_indr_item_list\">\r\n                                            <h2><a href=\"[field:arcurl /]\">[field:title /]</a></h2>\r\n                                            <div class=\"zt_indr_more\"><a href='{dede:field name=' typeurl '/}'>了解更多></a></div>\r\n                                        </div>\r\n                                    </div>\r\n                                </div>\r\n                                ",2363,3208);
$z[8]=Array("include","",5463,5502);
$z[8][4]['filename']="footBase.htm";
$z[9]=Array("include","",5520,5566);
$z[9][4]['filename']="bottomBaseRefer.htm";

?>