<?php
$z[0]=Array("field","",111,133);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",174,196);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",236,287);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",455,495);
$z[3][4]['filename']="headquote.htm";
$z[4]=Array("include","",560,595);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename/]",1151,1191);
$z[6]=Array("field","",1324,1353);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n				<li>      				\r\n					<h3><a href=\"[field:arcurl/]\" >☆ [field:title/]</a></h3>\r\n                    <p>[field:description/]...</p>\r\n					<span>\r\n					    <a href=\"[field:arcurl/]\">[field:global.cfg_basehost/][field:arcurl/]</a>\r\n						<small>分类：</small><a href=\"[field:typeurl/]\" >[field:typename/]</a>\r\n						<small>点击：</small>[field:click/]\r\n						<small>日期：</small>[field:stime/]\r\n					</span>\r\n				</li></br></br>\r\n			",1582,2066);
$z[7][4]['perpage']="20";
$z[8]=Array("pagelist","",2134,2163);
$z[8][4]['listsize']="4";
$z[9]=Array("include","",2287,2324);
$z[9][4]['filename']="footer.htm";

?>