<?php
$z[0]=Array("field","",111,130);
$z[0][4]['name']="title";
$z[1]=Array("global","",131,157);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",198,220);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",260,311);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",835,870);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typename/]",1420,1460);
$z[6]=Array("field","",1597,1626);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n				<li>      				\r\n					<h3><a href=\"[field:arcurl/]\" target=\"_blank\">☆&nbsp;[field:title/]</a></h3>\r\n                    <p>[field:description/]...</p>\r\n					<span>\r\n					    <a href=\"[field:arcurl/]\">[field:global.cfg_basehost/][field:arcurl/]</a>\r\n						<small>分类：</small><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a>\r\n						<small>点击：</small>[field:click/]\r\n						<small>日期：</small>[field:stime/]\r\n					</span>\r\n				</li></br></br>\r\n			",1855,2373);
$z[7][4]['perpage']="20";
$z[8]=Array("pagelist","",2441,2470);
$z[8][4]['listsize']="4";
$z[9]=Array("include","",2594,2631);
$z[9][4]['filename']="footer.htm";

?>